name: plex-watch-together
services:
  - name: web
    source_dir: /
    github:
      repo: doug12r/Code
      branch: main
      deploy_on_push: true
    build_command: ./scripts/app-platform-build.sh
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 2
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: REPLACE_WITH_32_CHAR_SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SKIP_ENV_VALIDATION
        value: "true"

databases:
  - name: db
    engine: PG
    version: "15"
    size_slug: db-s-dev-database
    num_nodes: 1

static_sites: []
workers: []
jobs: []