# Production App Platform Configuration
name: plex-watch-together-prod
services:
  - name: web
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/plex-watch-together
      branch: main
      deploy_on_push: true
    build_command: |
      npm ci --only=production
      npx prisma generate
      npm run build
    run_command: node server.js
    environment_slug: node-js
    instance_count: 2  # Multiple instances for high availability
    instance_size_slug: basic-s  # Larger instances
    http_port: 3001
    routes:
      - path: /
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 2
    # Auto-scaling configuration
    autoscaling:
      min_instance_count: 1
      max_instance_count: 5
      cpu_threshold_percent: 80
      memory_threshold_percent: 80
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: REPLACE_WITH_32_CHAR_SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_METRICS
        value: "true"

databases:
  - name: db
    engine: PG
    version: "15"
    size_slug: db-s-2vcpu-4gb  # Larger database for production
    num_nodes: 1

static_sites: []
workers: []
jobs: []